---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - batch.k8s.learning.yodo.dev
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.k8s.learning.yodo.dev
  resources:
  - cronjobs/finalizers
  verbs:
  - update
- apiGroups:
  - batch.k8s.learning.yodo.dev
  resources:
  - cronjobs/status
  verbs:
  - get
  - patch
  - update
