apiVersion: batch.k8s.learning.yodo.dev/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: cronctl
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-sample
spec:
  # TODO(user): Add fields here
